name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      dotnet-working-directory: ./ThePeopleSearch
      dotnet-test-directory: ./ThePeopleSearch_Test
      angular-working-directory: ./ThePeopleSearch/ClientApp

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.dotnet-working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.dotnet-working-directory}}
    - name: Test .Net
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.dotnet-test-directory}}    
